### ISSUE TITLE
Install stuck

### ISSUE THREAD

**Issue by redheadontherun** [rshipp/python-dshield#4]
installation is stuck at processing triggers for menu...

see attachment

![image](https://cloud.githubusercontent.com/assets/8294330/13014631/a9fb6848-d169-11e5-85bc-dba504f1e734.png)

only error is "pip: not found"

**Comment by rshipp** [comment]
It looks like you're trying to install from apt. What distro is this? I wasn't aware anyone had tried to package it.

**Comment by redheadontherun** [comment]
I'm not sure, just following Johannes Ullrich instructions on isc.sans.org. 

Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by redheadontherun** [comment]
https://isc.sans.edu/forums/diary/Beta+Testers+Wanted+Use+a+Raspberry+Pi+as+a+DShield+Sensor/20717/
Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by rshipp** [comment]
Ah, that's not related to this repo. You're looking for https://github.com/DShield-ISC/dshield.

**Comment by rshipp** [comment]
The fix is probably just to `sudo apt-get install python-dev`, but you should report this on the issues there so @jullrich can fix it for other people.

**Comment by redheadontherun** [comment]
Thanks for the heads up!


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by jullrich** [comment]
Can you fill me in on the details?

**Comment by rshipp** [comment]
@jullrich Looks like @redheadontherun was trying to follow your instructions, but since pip was not installed on the Pi, it errored out. I would guess installing pip before running the install command would fix this.

**Comment by redheadontherun** [comment]
Looks like I was able to get it installed. How should I verify it's working?


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by jullrich** [comment]
when you log into your account at dshield.org (or isc.sans.edu), you should see the reports. Also grep for “dshield” in /var/log/syslog to check for errors.

Thanks for trying it out!



> On Feb 12, 2016, at 9:17 PM, redheadontherun <notifications@github.com> wrote:
> 
> 
> 
> Looks like I was able to get it installed. How should I verify it's working?
> 
> 
> Sent from my T-Mobile 4G LTE Device
> 
> -------- Original message --------
> From: Johannes Ullrich <notifications@github.com>
> Date: 2/12/2016 3:41 PM (GMT-08:00)
> To: rshipp/python-dshield <python-dshield@noreply.github.com>
> Cc: redheadontherun <redheadontherun@gmail.com>
> Subject: Re: [python-dshield] Install stuck (#4)
> 
> Can you fill me in on the details?
> 
> 
> 
> > On Feb 12, 2016, at 6:36 PM, redheadontherun <notifications@github.com> wrote:
> 
> >
> 
> >
> 
> >
> 
> > Thanks for the heads up!
> 
> >
> 
> >
> 
> > Sent from my T-Mobile 4G LTE Device
> 
> >
> 
> > -------- Original message --------
> 
> > From: Ryan Shipp <notifications@github.com>
> 
> > Date: 2/12/2016 12:16 PM (GMT-08:00)
> 
> > To: rshipp/python-dshield <python-dshield@noreply.github.com>
> 
> > Cc: redheadontherun <redheadontherun@gmail.com>
> 
> > Subject: Re: [python-dshield] Install stuck (#4)
> 
> >
> 
> > The fix is probably just to sudo apt-get install python-dev, but you should report this on the issues there so @jullrich can fix it for other people.
> 
> >
> 
> > —
> 
> > Reply to this email directly or view it on GitHub.
> 
> >
> 
> >
> 
> >
> 
> >
> 
> >
> 
> >
> 
> >
> 
> > —
> 
> > Reply to this email directly or view it on GitHub.
> 
> >
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 
> 
> 
> 
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Don’t miss SANS 2016, March 12-21, in Orlando at the Walt Disney World Dolphin Resort. Choose from more than 35 hands-on Infosec courses taught by SANS incomparable Instructors plus bonus sessions, vendor expo, and challenging Core and DFIR NetWars competitions!
http://www.sans.org/u/avu
